---

- name: Airflow | Ensure Airflow group
  group:
    name: "{{ airflow_group }}"

- name: Airflow | Ensure Airflow user
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    shell: /bin/bash

- name: Airflow | Create path for Airflow home
  file:
    path: "{{ airflow_home }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Create path for venv
  file:
    path: "{{ airflow_virtualenv }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    state: directory

- name: Airflow | Create path for configuration files
  file:
    path: "{{ airflow_environment_file_folder }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Create path for PID files
  file:
    path: "{{ airflow_pidfile_folder }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: "{{ airflow_pip_executable }}"

- name: Airflow | Installing dependencies
  apt:
    pkg: "{{ airflow_required_libs }}"
    state: present
    update_cache: yes

- name: Airflow | Updating pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"

- name: Airflow | Avoiding bugs with setup tools
  pip:
    name: setuptools
    state: latest
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"

- name: Airflow | Installing proper Celery version
  pip:
    name: celery
    version: "{{ celery_version }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  when: airflow_executor == "CeleryExecutor"

- name: Airflow | Installing extra Celery packages
  pip:
    name: celery[{{ item }}]
    version: "{{ celery_version }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  with_items: "{{ celery_extra_packages }}"
  when: airflow_executor == "CeleryExecutor" and celery_extra_packages

- name: Airflow | Set AIRFLOW_HOME environment variable in /etc/environment
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME={{ airflow_home }}'

- name: Airflow | Installing Airflow
  pip:
    name: apache-airflow
    version: "{{ airflow_version }}"
    extra_args: --no-cache-dir
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  register: airflow_install
  environment:
    SLUGIFY_USES_TEXT_UNIDECODE: "yes"

- name: Airflow | Installing Airflow Extra Packages (prior to Ansible 2.7)
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: "apache-airflow[{{ item }}]=={{ airflow_version }}"
  with_items: "{{ airflow_extra_packages }}"
  when: 
    - airflow_extra_packages
    - ansible_version.full is version_compare('2.7', '<')

- name: Airflow | Installing Airflow Extra Packages
  pip:
    name: "apache-airflow[{{ airflow_extra_packages | join(', ') }}]"
    version: "{{ airflow_version }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  when:
  - airflow_extra_packages
  - ansible_version.full is version_compare('2.7', '>=')

- name: Airflow | Installing DAGs dependencies
  pip:
    name: "{{ dags_dependencies }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  when: dags_dependencies
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Copy Environment File
  template:
    src: airflow-environment-file.j2
    dest: "{{ airflow_environment_file_folder }}/airflow"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Copy Daemon scripts
  template:
    src: "{{ item.key }}.service.j2"
    dest: /lib/systemd/system/{{ item.key }}.service
    mode: 0644
  notify: restart {{ item.key }}
  with_dict: "{{ airflow_services }}"
  when: "item.value.enabled"
