---

- name: Airflow | Install
  include: install.yml
  tags:
    - install
    - airflow_install

- name: Airflow | Config
  include: config.yml
  tags:
    - config
    - airflow_config

- name: Airflow | Service
  include: service.yml
  tags:
    - service
    - airflow_service
